#ifndef ofxPedal_h
#define ofxPedal_h

#include "../libs/Pedal/include/pedal/pedal.hpp"
#include "AllPass.hpp"
#include "Biquad.hpp"
#include "Buffer.hpp"
#include "BufferPlayer.hpp"
#include "BufferTap.hpp"
#include "CircularBuffer.hpp"
#include "CombFilter.hpp"
#include "CTEnvelope.hpp"
#include "DebugTool.hpp"
#include "Delay.hpp"
#include "HanningWindow.hpp"
#include "HighPass.hpp"
#include "ImpulseGenerator.hpp"
#include "Interpolation.hpp"
#include "LowPass.hpp"
#include "LowPassCombFilter.hpp"
#include "MoorerReverb.hpp"
#include "pdlSettings.hpp"
#include "PinkNoise.hpp"
#include "TPhasor.hpp"
#include "TSaw.hpp"
#include "TSine.hpp"
#include "TSquare.hpp"
#include "TTriangle.hpp"
#include "utilities.hpp"
#include "WhiteNoise.hpp"
#include "WTSaw.hpp"
#include "WTSine.hpp"
#include "WTSquare.hpp"
#include "WTTriangle.hpp"

#endif